import argparse
import csv
from pathlib import Path

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt


METRICS = [
    ('d1_all', 'D1-all (%)'),
    ('epe', 'EPE'),
]

VALUE_MODES = {
    'raw': {
        'suffix': '',
        'label_prefix': '',
        'baseline_label': 'reference',
    },
    'delta-ref': {
        'suffix': '_delta_ref',
        'label_prefix': 'Delta ',
        'baseline_label': 'reference delta=0',
    },
    'delta-ref-pct': {
        'suffix': '_delta_ref_pct',
        'label_prefix': 'Delta ',
        'baseline_label': 'reference delta=0%',
    },
}


def parse_args():
    parser = argparse.ArgumentParser(
        description='Plot exposure/gain grid sweep curves from grid_metrics.csv.'
    )
    parser.add_argument(
        '--input-csv',
        type=str,
        required=True,
        help='Path to grid_metrics.csv generated by grid_exposure_gain_raftstereo.py.')
    parser.add_argument(
        '--output-path',
        type=str,
        required=True,
        help='Target image path, for example output/plots/exposure_gain_grid_curves.png.')
    parser.add_argument(
        '--title',
        type=str,
        default='Exposure/Gain vs Stereo Matching Performance',
        help='Figure title.')
    parser.add_argument(
        '--mode',
        type=str,
        choices=['gain', 'full'],
        default='gain',
        help='Use gain for gain-vs-performance curves, or full for exposure and gain panels.')
    parser.add_argument(
        '--value-mode',
        type=str,
        choices=sorted(VALUE_MODES.keys()),
        default='raw',
        help='Plot raw metrics, metric delta to reference, or percent delta to reference.')
    return parser.parse_args()


def read_rows(path):
    with open(path, 'r', newline='') as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError(f'No rows found in {path}')

    parsed = []
    for row in rows:
        parsed_row = {
            'exposure_ms': float(row['exposure_ms']),
            'gain': float(row['gain']),
        }
        for metric_name, _ in METRICS:
            for suffix in ['', '_delta_ref', '_delta_ref_pct']:
                key = f'{metric_name}{suffix}'
                if key in row and row[key] != '':
                    parsed_row[key] = float(row[key])
        parsed.append(parsed_row)
    return parsed


def try_read_reference(csv_path):
    reference_path = Path(csv_path).resolve().parent / 'reference_metrics.csv'
    if not reference_path.exists():
        return None
    with open(reference_path, 'r', newline='') as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        return None

    row = rows[0]
    return {
        'd1_all': float(row['d1_all']),
        'epe': float(row['epe']),
    }


def build_series(rows, axis_key, label_key):
    label_values = sorted({row[label_key] for row in rows})
    series = []
    for label_value in label_values:
        subset = [row for row in rows if row[label_key] == label_value]
        subset.sort(key=lambda item: item[axis_key])
        series.append((label_value, subset))
    return series


def metric_column(metric_name, value_mode):
    return f'{metric_name}{VALUE_MODES[value_mode]["suffix"]}'


def metric_axis_label(metric_label, value_mode):
    if value_mode == 'delta-ref-pct':
        return f'{VALUE_MODES[value_mode]["label_prefix"]}{metric_label} vs reference (%)'
    if value_mode == 'delta-ref':
        return f'{VALUE_MODES[value_mode]["label_prefix"]}{metric_label} vs reference'
    return metric_label


def assert_metric_columns(rows, value_mode):
    missing = []
    for metric_name, _ in METRICS:
        key = metric_column(metric_name, value_mode)
        if any(key not in row for row in rows):
            missing.append(key)
    if missing:
        raise ValueError(
            f'Missing columns for value-mode={value_mode}: {sorted(set(missing))}'
        )


def add_baseline(axis, metric_name, value_mode, reference_metrics):
    if value_mode == 'raw':
        if reference_metrics is None:
            return
        axis.axhline(
            y=reference_metrics[metric_name],
            color='0.35',
            linestyle='--',
            linewidth=1.5,
            label=f'reference {metric_name}={reference_metrics[metric_name]:.4f}',
        )
        return

    axis.axhline(
        y=0.0,
        color='0.35',
        linestyle='--',
        linewidth=1.5,
        label=VALUE_MODES[value_mode]['baseline_label'],
    )


def plot_curves(rows, output_path, title, value_mode, reference_metrics=None):
    assert_metric_columns(rows, value_mode)
    exposure_series = build_series(rows, axis_key='exposure_ms', label_key='gain')
    gain_series = build_series(rows, axis_key='gain', label_key='exposure_ms')

    fig, axes = plt.subplots(2, 2, figsize=(16, 10), dpi=180)

    for col, (metric_name, metric_label) in enumerate(METRICS):
        axis = axes[0, col]
        y_key = metric_column(metric_name, value_mode)
        for gain_db, points in exposure_series:
            axis.plot(
                [item['exposure_ms'] for item in points],
                [item[y_key] for item in points],
                marker='o',
                linewidth=2.0,
                markersize=4.5,
                label=f'gain={gain_db:g} dB',
            )
        add_baseline(axis, metric_name, value_mode, reference_metrics)
        axis.set_xlabel('Exposure (ms)')
        axis.set_ylabel(metric_axis_label(metric_label, value_mode))
        axis.grid(True, linestyle='--', alpha=0.35)
        axis.legend()

    for col, (metric_name, metric_label) in enumerate(METRICS):
        axis = axes[1, col]
        y_key = metric_column(metric_name, value_mode)
        for exposure_ms, points in gain_series:
            axis.plot(
                [item['gain'] for item in points],
                [item[y_key] for item in points],
                marker='o',
                linewidth=2.0,
                markersize=4.5,
                label=f'exposure={exposure_ms:g} ms',
            )
        add_baseline(axis, metric_name, value_mode, reference_metrics)
        axis.set_xlabel('Gain (dB)')
        axis.set_ylabel(metric_axis_label(metric_label, value_mode))
        axis.grid(True, linestyle='--', alpha=0.35)
        axis.legend()

    fig.suptitle(title)
    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, bbox_inches='tight')
    plt.close(fig)


def plot_gain_curves(rows, output_path, title, value_mode, reference_metrics=None):
    assert_metric_columns(rows, value_mode)
    gain_series = build_series(rows, axis_key='gain', label_key='exposure_ms')

    fig, axes = plt.subplots(1, 2, figsize=(14, 5), dpi=180)

    for axis, (metric_name, metric_label) in zip(axes, METRICS):
        y_key = metric_column(metric_name, value_mode)
        for exposure_ms, points in gain_series:
            axis.plot(
                [item['gain'] for item in points],
                [item[y_key] for item in points],
                marker='o',
                linewidth=2.0,
                markersize=4.5,
                label=f'exposure={exposure_ms:g} ms',
            )
        add_baseline(axis, metric_name, value_mode, reference_metrics)
        axis.set_xlabel('Gain (dB)')
        axis.set_ylabel(metric_axis_label(metric_label, value_mode))
        axis.grid(True, linestyle='--', alpha=0.35)
        axis.legend()

    fig.suptitle(title)
    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, bbox_inches='tight')
    plt.close(fig)


def main():
    args = parse_args()
    input_csv = Path(args.input_csv).resolve()
    output_path = Path(args.output_path).resolve()
    rows = read_rows(input_csv)
    reference_metrics = try_read_reference(input_csv)
    if args.mode == 'full':
        plot_curves(
            rows,
            output_path,
            args.title,
            value_mode=args.value_mode,
            reference_metrics=reference_metrics,
        )
    else:
        plot_gain_curves(
            rows,
            output_path,
            args.title,
            value_mode=args.value_mode,
            reference_metrics=reference_metrics,
        )
    print(f'[plot] saved figure to {output_path}', flush=True)


if __name__ == '__main__':
    main()
